### ISSUE TITLE
EventMachine error

### ISSUE THREAD

**Issue by cmelbye** [mojombo/proxymachine#1]
I'm getting the following error when I try to do `telnet localhost 5432`:

```
iMac:proxy charlie$ proxymachine -c master.rb 
I, [2009-11-01T13:12:00.695943 #13925]  INFO -- : Listening on 0.0.0.0:5432
I, [2009-11-01T13:12:00.696042 #13925]  INFO -- : Send QUIT to quit after waiting for all connections to finish.
I, [2009-11-01T13:12:00.696076 #13925]  INFO -- : Send TERM or INT to quit after waiting for up to 10 seconds for connections to finish.
I, [2009-11-01T13:12:05.045182 #13925]  INFO -- : Uncaught exception
I, [2009-11-01T13:12:05.045273 #13925]  INFO -- : undefined method `associate_callback_target' for #<EventMachine::Protocols::ClientConnection:0x11eb378>
I, [2009-11-01T13:12:05.045530 #13925]  INFO -- : /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/em/connection.rb:39:in `new'
/Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/em/connection.rb:36:in `instance_eval'
/Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/em/connection.rb:36:in `new'
/Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:1430:in `event_callback'
/Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
/Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
/Library/Ruby/Gems/1.8/gems/proxymachine-1.0.0/bin/../lib/proxymachine.rb:81:in `run'
/Library/Ruby/Gems/1.8/gems/proxymachine-1.0.0/bin/proxymachine:36
/usr/bin/proxymachine:19:in `load'
/usr/bin/proxymachine:19
```

I'm using proxymachine 1.0.0 and eventmachine 0.12.10.

**Comment by jakedouglas** [comment]
I'm not able to reproduce this on 1.8.7 or 1.9.1 using these versions. Can you please give more details about what Ruby you are using and also show us the code in master.rb? Thanks

**Comment by cmelbye** [comment]
This error isn't coming up anymore, I think it was a problem with my RubyGems/Rip installation. Closing issue.
